from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db import transaction
from django.db.models import Q

from circulation.models import Loan, Reservation
from reviews.models import Rating, Review
from catalog.models import Book, Author

User = get_user_model()


class Command(BaseCommand):
    help = "Remove demo operational data generated by seed_operational_data command."

    def add_arguments(self, parser):
        parser.add_argument("--reader-prefix", default="reader", help="Prefix for demo reader usernames.")
        parser.add_argument("--librarian-prefix", default="librarian", help="Prefix for demo librarian usernames.")
        parser.add_argument(
            "--remove-generated-books",
            action="store_true",
            help="Also remove generated demo books (title starts with 'Testovací kniha ').",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Print what would be deleted without changing the database.",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        reader_prefix = options["reader_prefix"]
        librarian_prefix = options["librarian_prefix"]
        dry_run = options["dry_run"]
        remove_generated_books = options["remove_generated_books"]

        demo_users = User.objects.filter(
            Q(username__startswith=reader_prefix) | Q(username__startswith=librarian_prefix)
        )
        demo_user_ids = list(demo_users.values_list("id", flat=True))

        ratings_qs = Rating.objects.filter(user_id__in=demo_user_ids)
        reviews_qs = Review.objects.filter(user_id__in=demo_user_ids)
        reservations_qs = Reservation.objects.filter(requester_id__in=demo_user_ids)
        loans_qs = Loan.objects.filter(
            Q(borrower_id__in=demo_user_ids) | Q(handled_by_id__in=demo_user_ids)
        )

        generated_books_qs = Book.objects.filter(title__startswith="Testovací kniha ")
        generated_book_ids = list(generated_books_qs.values_list("id", flat=True))

        if remove_generated_books and generated_book_ids:
            ratings_qs = Rating.objects.filter(Q(pk__in=ratings_qs.values("pk")) | Q(book_id__in=generated_book_ids))
            reviews_qs = Review.objects.filter(Q(pk__in=reviews_qs.values("pk")) | Q(book_id__in=generated_book_ids))
            reservations_qs = Reservation.objects.filter(
                Q(pk__in=reservations_qs.values("pk")) | Q(book_id__in=generated_book_ids)
            )
            loans_qs = Loan.objects.filter(Q(pk__in=loans_qs.values("pk")) | Q(book_id__in=generated_book_ids))

        stats = {
            "users": demo_users.count(),
            "ratings": ratings_qs.count(),
            "reviews": reviews_qs.count(),
            "reservations": reservations_qs.count(),
            "loans": loans_qs.count(),
            "generated_books": generated_books_qs.count() if remove_generated_books else 0,
        }

        self.stdout.write("Nalezená demo provozní data:")
        self.stdout.write(f"- Uživatelé: {stats['users']}")
        self.stdout.write(f"- Hodnocení: {stats['ratings']}")
        self.stdout.write(f"- Recenze: {stats['reviews']}")
        self.stdout.write(f"- Rezervace: {stats['reservations']}")
        self.stdout.write(f"- Výpůjčky: {stats['loans']}")
        if remove_generated_books:
            self.stdout.write(f"- Generované knihy: {stats['generated_books']}")

        if dry_run:
            self.stdout.write(self.style.WARNING("Dry-run: databáze nebyla změněna."))
            transaction.set_rollback(True)
            return

        deleted_loans = loans_qs.delete()[0]
        deleted_reservations = reservations_qs.delete()[0]
        deleted_ratings = ratings_qs.delete()[0]
        deleted_reviews = reviews_qs.delete()[0]

        deleted_books = 0
        deleted_authors = 0
        if remove_generated_books:
            deleted_books = generated_books_qs.delete()[0]
            generated_authors = Author.objects.filter(
                biography__startswith="Biografie autora ",
                books__isnull=True,
            ).distinct()
            deleted_authors = generated_authors.delete()[0]

        deleted_users = demo_users.delete()[0]

        self.stdout.write(self.style.SUCCESS("Reset demo provozních dat dokončen."))
        self.stdout.write(f"Odstraněno záznamů (výpůjčky): {deleted_loans}")
        self.stdout.write(f"Odstraněno záznamů (rezervace): {deleted_reservations}")
        self.stdout.write(f"Odstraněno záznamů (hodnocení): {deleted_ratings}")
        self.stdout.write(f"Odstraněno záznamů (recenze): {deleted_reviews}")
        if remove_generated_books:
            self.stdout.write(f"Odstraněno záznamů (knihy): {deleted_books}")
            self.stdout.write(f"Odstraněno záznamů (autoři): {deleted_authors}")
        self.stdout.write(f"Odstraněno záznamů (uživatelé): {deleted_users}")
