# Generated by Django 5.2.11 on 2026-02-27 22:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Death date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'birth_date'), name='unique_author_identity')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('isbn', models.CharField(help_text='Enter ISBN-10 or ISBN-13 without separators.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must contain 10 or 13 digits (X allowed for ISBN-10 check digit).', regex='^(?:97[89])?\\d{9}[\\dXx]$')], verbose_name='ISBN')),
                ('publication_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1450), django.core.validators.MaxValueValidator(2028)], verbose_name='Publication year')),
                ('language', models.CharField(choices=[('cs', 'Czech'), ('en', 'English'), ('sk', 'Slovak'), ('de', 'German'), ('other', 'Other')], default='cs', max_length=10, verbose_name='Language')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('copies_total', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total copies')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='catalog.author', verbose_name='Authors')),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='catalog.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Title')),
                ('attachment_type', models.CharField(choices=[('cover', 'Cover'), ('sample_pdf', 'Sample PDF'), ('other', 'Other')], default='other', max_length=20, verbose_name='Attachment type')),
                ('file', models.FileField(upload_to='book_attachments/%Y/%m/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='catalog.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Book attachment',
                'verbose_name_plural': 'Book attachments',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['attachment_type'], name='book_attach_type_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='book_title_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year'], name='book_year_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_available'], name='book_available_idx'),
        ),
    ]
